### ISSUE TITLE
Codecov configuration correction

### ISSUE THREAD

**Issue by K20shores** [NCAR/chemistry-cafe#79]
While the [codecov reports](https://app.codecov.io/gh/NCAR/chemistry-cafe) are uploaded, you cannot click through files to see what is covered and what is not. For reference, our [micm](https://github.com/NCAR/micm) repository has a [properly configured set of codecov reports](https://app.codecov.io/gh/NCAR/micm).

**Acceptance Criteria**
- Files covered by tests can be clicked through in codecov
- Coverage for the backend files are viewable. (required)
- Coverage for the frontend files are viewable. (desired, if possible)

**Ideas**
- Update [codecov.yml](https://github.com/NCAR/chemistry-cafe/blob/main/codecov.yml) and check if the [paths](https://docs.codecov.com/docs/codecovyml-reference#coveragestatus) attribute of the codecov file spec can fix this.
- If possible, add coverage reports for both frontend and backend.

**Comment by K20shores** [comment]
ChatGPT seems to think you can use something like this. Of course, proper paths would be needed

```
coverage:
  precision: 2
  round: down

comment: false

flags:
  frontend: 
    paths:
      - frontend
  backend:
    paths:
      - backend

uploads:
  - target: coverage
    flags: frontend
    path: frontend/coverage/lcov.info
  - target: coverage
    flags: backend
    path: backend/coverage/lcov.info

```
